<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYboxb9q\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYboxb9q/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYboxb9q.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYboxb9q\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYboxb9q\appProdProjectContainer([
    'container.build_hash' => 'Yboxb9q',
    'container.build_id' => '622c3c70',
    'container.build_time' => 1639770487,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYboxb9q');
