<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWwh6lex\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWwh6lex/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWwh6lex.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWwh6lex\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWwh6lex\appProdProjectContainer([
    'container.build_hash' => 'Wwh6lex',
    'container.build_id' => '56299715',
    'container.build_time' => 1639495228,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWwh6lex');
